#define USIPY_HF_generic            0
#define USIPY_HF_ACCEPT             1
#define USIPY_HF_ALLOW              2
#define USIPY_HF_ALSO               3
#define USIPY_HF_AUTHORIZATION      4
#define USIPY_HF_CCDIVERSION        5
#define USIPY_HF_CSEQ               6
#define USIPY_HF_CALLID             7
#define USIPY_HF_CONTACT            8
#define USIPY_HF_CONTENTLENGTH      9
#define USIPY_HF_CONTENTTYPE        10
#define USIPY_HF_DIVERSION          11
#define USIPY_HF_EXPIRES            12
#define USIPY_HF_FROM               13
#define USIPY_HF_MAXFORWARDS        14
#define USIPY_HF_PASSERTEDIDENTITY  15
#define USIPY_HF_PROXYAUTHENTICATE  16
#define USIPY_HF_PROXYAUTHORIZATION 17
#define USIPY_HF_RACK               18
#define USIPY_HF_RSEQ               19
#define USIPY_HF_REASON             20
#define USIPY_HF_RECORDROUTE        21
#define USIPY_HF_REFERTO            22
#define USIPY_HF_REFERREDBY         23
#define USIPY_HF_REPLACES           24
#define USIPY_HF_ROUTE              25
#define USIPY_HF_SERVER             26
#define USIPY_HF_SUPPORTED          27
#define USIPY_HF_TO                 28
#define USIPY_HF_USERAGENT          29
#define USIPY_HF_VIA                30
#define USIPY_HF_WWWAUTHENTICATE    31
#define USIPY_HF_WARNING            32
#define USIPY_HF_CALLID_c           33
#define USIPY_HF_CONTACT_c          34
#define USIPY_HF_CONTENTLENGTH_c    35
#define USIPY_HF_CONTENTTYPE_c      36
#define USIPY_HF_FROM_c             37
#define USIPY_HF_REFERTO_c          38
#define USIPY_HF_SUPPORTED_c        39
#define USIPY_HF_TO_c               40
#define USIPY_HF_VIA_c              41
#define USIPY_HF_max                41
