static const struct usipy_fast_parser hdr_pdata = {
    .magic = 0x46,
    .toid = {
      USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic,
      USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_SUPPORTED,
      USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic,
      USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic,
      USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic,
      USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic,
      USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic,
      USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic,
      USIPY_HF_generic, USIPY_HF_FROM_c, USIPY_HF_generic, USIPY_HF_generic,
      USIPY_HF_REFERTO, USIPY_HF_generic, USIPY_HF_CONTENTTYPE_c, USIPY_HF_RACK,
      USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_CALLID, USIPY_HF_CONTENTLENGTH_c,
      USIPY_HF_CONTACT_c, USIPY_HF_generic, USIPY_HF_SUPPORTED_c, USIPY_HF_generic,
      USIPY_HF_CALLID_c, USIPY_HF_VIA_c, USIPY_HF_generic, USIPY_HF_TO_c,
      USIPY_HF_generic, USIPY_HF_REFERTO_c, USIPY_HF_generic, USIPY_HF_generic,
      USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic,
      USIPY_HF_generic, USIPY_HF_WARNING, USIPY_HF_generic, USIPY_HF_generic,
      USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_PROXYAUTHORIZATION,
      USIPY_HF_FROM, USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic,
      USIPY_HF_CCDIVERSION, USIPY_HF_CONTACT, USIPY_HF_generic, USIPY_HF_generic,
      USIPY_HF_VIA, USIPY_HF_generic, USIPY_HF_REFERREDBY, USIPY_HF_generic,
      USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic,
      USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic,
      USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic,
      USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic,
      USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic,
      USIPY_HF_generic, USIPY_HF_CSEQ, USIPY_HF_generic, USIPY_HF_RSEQ,
      USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_CONTENTTYPE, USIPY_HF_generic,
      USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic,
      USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic,
      USIPY_HF_generic, USIPY_HF_EXPIRES, USIPY_HF_generic, USIPY_HF_AUTHORIZATION,
      USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_PASSERTEDIDENTITY,
      USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic,
      USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic,
      USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_ALSO, USIPY_HF_generic,
      USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic,
      USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_CONTENTLENGTH,
      USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_REPLACES, USIPY_HF_generic,
      USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic,
      USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic,
      USIPY_HF_TO, USIPY_HF_REASON, USIPY_HF_generic, USIPY_HF_generic,
      USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic,
      USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_USERAGENT, USIPY_HF_generic,
      USIPY_HF_generic, USIPY_HF_RECORDROUTE, USIPY_HF_generic,
      USIPY_HF_WWWAUTHENTICATE, USIPY_HF_generic, USIPY_HF_generic,
      USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic,
      USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic,
      USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic,
      USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_SERVER, USIPY_HF_ACCEPT,
      USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic,
      USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic,
      USIPY_HF_generic, USIPY_HF_ALLOW, USIPY_HF_generic, USIPY_HF_generic,
      USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic,
      USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic,
      USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic,
      USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic,
      USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic,
      USIPY_HF_PROXYAUTHENTICATE, USIPY_HF_generic, USIPY_HF_generic,
      USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic,
      USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic,
      USIPY_HF_generic, USIPY_HF_MAXFORWARDS, USIPY_HF_generic, USIPY_HF_generic,
      USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic,
      USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic,
      USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_ROUTE, USIPY_HF_generic,
      USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic, USIPY_HF_generic,
      USIPY_HF_generic, USIPY_HF_DIVERSION, USIPY_HF_generic, USIPY_HF_generic,
      USIPY_HF_generic
    }
};
