name: Debian Packages

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_dpkgs:
    uses: sippy/cimagic/.github/workflows/BuildDPKGs.yml@master
    with:
      apt_depends: cmake libx11-dev libsdl2-dev pkg-config zlib1g-dev
      submodules_recursive: true
      test_dpkgs_script: ./scripts/do-test-run.sh
