name: Debian Packages

on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:
  workflow_call:
    outputs:
      package_artifacts:
        description: Package artifact names uploaded by this workflow.
        value: ${{ jobs.build_dpkgs.outputs.dpkgs_artifacts }}

jobs:
  build_dpkgs:
    uses: sippy/cimagic/.github/workflows/BuildDPKGs.yml@master
    with:
      apt_depends: cmake libx11-dev libsdl2-dev pkg-config zlib1g-dev
      submodules_recursive: true
      test_dpkgs_script: ./scripts/do-test-run.sh
