# This is a basic workflow to help you get started with Actions

name: Check Python Integration

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
  pull_request:
    branches:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  python:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      COMPILER: ${{ matrix.compiler }}

    strategy:
      matrix:
        compiler: ['gcc-10', 'gcc-11', 'gcc-12', 'gcc-13', 'gcc-14', 'clang-13', 'clang-14', 'clang-15', 'clang-16']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: before_install
        run: sudo -H DEBIAN_FRONTEND=noninteractive apt-get update

      - name: Workaround for tar not being able to access /var/cache/apt/archives
        run: sudo chmod u+s "$(command -v tar)"

      # Cache the apt-get packages
      - name: Cache apt-get packages
        uses: actions/cache@v3
        with:
          path: /var/cache/apt/archives
          key: ${{ matrix.os }}-apt-get-${{ hashFiles('**/apt-get-requirement.txt') }}

      # Install the apt-get packages
      - name: Install apt-get packages
        run: cat apt-get-requirement.txt | xargs sudo apt-get -yq --no-install-recommends install

      - name: Build 
        run: python setup.py build

      - name: Pip install
        run: |
          python -m pip install --upgrade pip
          rm -rf build
          pip install .

      - name: Test
        run: |
          pip install -r tests/requirements.txt
          python tests/test_python.py
